## Ejemplo de Clases
### EDTT

In [33]:
import numpy as np

In [34]:
M_A = np.array([[2,-1], 
              [-1,1]])
A=np.copy(M_A)
print('A=',M_A)
Fil = M_A.shape[0]
print('filas:',Fil)
Col = M_A.shape[1]
##Crear. matriz identidad
Iden=np.identity(Fil)
print('I:= ',Iden)
#Crear matrices vacias R,Q
M_A_T=np.zeros((Fil,Col)) # Matriz vacia 
Ix=np.zeros((Fil,Col)) # Matriz vacia 
Qt=np.zeros((Fil,Col)) # Matriz vacia Q transpuesta

A= [[ 2 -1]
 [-1  1]]
filas: 2
I:=  [[1. 0.]
 [0. 1.]]


In [35]:
M_A_T=np.transpose(M_A)
print('A transpuesta=',M_A_T)
Igual=np.array_equal(M_A,M_A_T)
print(Igual)
if Igual==True:
       print('Matriz simetrica')
else:
       print('Matriz no simetrica')

A transpuesta= [[ 2 -1]
 [-1  1]]
True
Matriz simetrica


In [36]:
#Verificacion Determinates
delta1=M_A[0,0]
delta2=M_A[0,0]*M_A[1,1]-M_A[0,1]*M_A[1,0]
print('delta1',delta1)
print('delta2',delta2)
if delta1 >=0 and delta2 >=0:
       print('Matriz semidedifinida positiva')
else:
       print('No cumple Matriz semidedifinida positiva')

delta1 2
delta2 1
Matriz semidedifinida positiva


In [42]:
from sympy import symbols
from sympy import *
x,y,z=symbols('x y z')
Ix=x*Iden
Ax=A-Ix
print(Ax)
delta3=Ax[0,0]*Ax[1,1]-Ax[0,1]*Ax[1,0]
print('Ecuacion P(x)',delta3)
delta3=simplify(delta3)
print('Ecuacion P(x)',delta3)


[[2 - 1.0*x -1]
 [-1 1 - 1.0*x]]
Ecuacion P(x) (1 - 1.0*x)*(2 - 1.0*x) - 1
Ecuacion P(x) 1.0*x**2 - 3.0*x + 1.0


In [43]:
solucionx=solve(delta3, x)
print(solucionx)

[0.381966011250105, 2.61803398874989]


## Las columnas son

In [122]:
Fil = M_A.shape[0]
x1=A[:,0]
x2=A[:,1]
x3=A[:,2]
print(x1,':',x2,':',x3)

[1 0 0 0] : [1 1 0 1] : [1 0 1 1]


In [123]:
#Calculando primera columna u1
x11=np.zeros((Fil))
N_x1 = np.linalg.norm(x1)
print('Norma x1: ',N_x1)
u1=x1/N_x1
print('u1 : ',u1)

Norma x1:  1.0
u1 :  [1. 0. 0. 0.]


In [124]:
#Calculando segunda columna u2
pi_x2u1=np.inner(x2,u1) ##Producto interno u1,v1
print('Producto interno x2,u1: ',pi_x2u1)
r2=x2-pi_x2u1*u1
N_r2 = np.linalg.norm(r2)
u2=r2/N_r2
print('r2: ',r2)
print('u2: ',u2)

Producto interno x2,u1:  1.0
r2:  [0. 1. 0. 1.]
u2:  [0.         0.70710678 0.         0.70710678]


In [125]:
#Calculando tercera columna u3
pi_x3u1=np.inner(x3,u1) ##Producto interno x3,u1
print('Producto interno x3,u1: ',pi_x3u1)
pi_x3u2=np.inner(x3,u2) ##Producto interno x3,u2
print('Producto interno x3,u1: ',pi_x3u2)
r3=x3-pi_x3u1*u1-pi_x3u2*u2
N_r3 = np.linalg.norm(r3)
u3=r3/N_r3
print('r3: ',r3)
print('u3: ',u3)

Producto interno x3,u1:  1.0
Producto interno x3,u1:  0.7071067811865475
r3:  [ 0.  -0.5  1.   0.5]
u3:  [ 0.         -0.40824829  0.81649658  0.40824829]


In [126]:
Q[:,0]=u1
Q[:,1]=u2
Q[:,2]=u3
print('Q: ',Q)
print('--------')
Qt=np.transpose(Q) ## Esto se aplica porque Q*=(Qconjujado)^T = Conjugado(Q^T)
print('Q*: ',Qt)
print('--------')
R=np.matmul(Qt,M_A )
print('R: ',R)

Q:  [[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.40824829]
 [ 0.          0.          0.81649658]
 [ 0.          0.70710678  0.40824829]]
--------
Q*:  [[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.         -0.40824829  0.81649658  0.40824829]]
--------
R:  [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.41421356e+00 7.07106781e-01]
 [0.00000000e+00 1.66533454e-16 1.22474487e+00]]


In [127]:
#Comprobacion de las matrices Q*R
A=np.matmul(Q,R)
print(np.round(A))

[[ 1.  1.  1.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]
 [ 0.  1.  1.]]
