## Matrices


In [1]:
import numpy as np

In [2]:
M_A = np.array([[-1, 3,1,0], 
              [1,-3,2,1], 
              [3,1,0,1],
             [2,1,0,0]])
A=np.copy(M_A)
print('A=',M_A)
Fil = M_A.shape[0]
print('filas:',Fil)
Col = M_A.shape[1]
##Crear. matriz identidad
Iden=np.identity(Fil)
print('I:= ',Iden)

A= [[-1  3  1  0]
 [ 1 -3  2  1]
 [ 3  1  0  1]
 [ 2  1  0  0]]
filas: 4
I:=  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
C_fact=np.copy(M_A[:,0]) #Extrae los cofactores de  primer columna
print('cofactores=',C_fact)
matriz = [range(Col) for i in range(Fil)]
Aux_1=np.identity(Fil)
Aux_2=np.zeros((Fil,Col)) # Matriz vacia de 10 pasos
indice=1
print('------------------')
for i in range(1,Fil): #Comienza desde fila 2 : [1,:]
    Id1=np.copy(Iden)
    M_A[i,:]=C_fact[i]*M_A[0,:]-C_fact[0]*M_A[i,:] #Fila2 =cofactor-fila1
    Id1[i,:]=C_fact[i]*Id1[0,:]-C_fact[0]*Id1[i,:] #Fila2 =cofactor-fila1
    Idinv1=np.linalg.inv(Id1)
    Aux_2=np.matmul(Aux_1,Idinv1)
    Aux_1=Aux_2
    print('Fila',i+1,':',C_fact[i],'*Fila 1-',C_fact[0],'*Fila',i+1)
    print('Pivoteo- A: =',M_A)
    print('Matriz elemental',indice,':=',Id1)
    indice=indice +1
    print('Matriz inversa elemental',indice,':=',Idinv1)
    print('Producto Matrices inversa elemental: =',Aux_1)
    print('------------------------')

cofactores= [-1  1  3  2]
------------------
Fila 2 : 1 *Fila 1- -1 *Fila 2
Pivoteo- A: = [[-1  3  1  0]
 [ 0  0  3  1]
 [ 3  1  0  1]
 [ 2  1  0  0]]
Matriz elemental 1 := [[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz inversa elemental 2 := [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Producto Matrices inversa elemental: = [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
------------------------
Fila 3 : 3 *Fila 1- -1 *Fila 3
Pivoteo- A: = [[-1  3  1  0]
 [ 0  0  3  1]
 [ 0 10  3  1]
 [ 2  1  0  0]]
Matriz elemental 2 := [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [3. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz inversa elemental 3 := [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-3. -0.  1. -0.]
 [ 0.  0.  0.  1.]]
Producto Matrices inversa elemental: = [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [-3.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
------------------------
Fila 4 : 2 *Fila 1- -1 *Fila 4
Pivoteo- A: = [[-1  3  1  0]
 [ 0  0  3  1]
 [ 0 1

In [4]:
##Crear. matriz identidad
Iden=np.identity(Fil)
C_fact=np.copy(M_A[:,1]) #Extrae los cofactores de  segunda columna
print('cofactores 2da col=',C_fact)
matriz = [range(Col) for i in range(Fil)]
print('------------------')
Permuta=np.copy(Iden) ## Crea matriz de permutacion
Id1=np.copy(Iden)  ## Crea matriz idenitidad auxiliar
if C_fact[1]==0:  # Si el cofactor de la fila 2 es cero se permuta con la F3
        M_A[:,:]=M_A[[0,2,1,3],:]
        Permuta[:,:]=Permuta[[0,2,1,3],:] #Aplica matriz de permutaciones
        print('Matriz. permutada filas ',M_A)
        C_fact=np.copy(M_A[:,1]) #Extrae los cofactores de  segunda columna
        M_A[3,:]=C_fact[1]*M_A[3,:]-C_fact[3]*M_A[1,:] #Fila4 =CF*F4-CF*F2
        Id1[3,:]=C_fact[1]*Id1[3,:]-C_fact[3]*Id1[1,:] #Fila4 =CF*F4-CF*F2
        Idinv1=np.linalg.inv(Id1)
        Aux_2=np.matmul(Aux_1,Idinv1)
        Aux_1=Aux_2
        print('Fila',4,':',C_fact[1],'*Fila 4-',C_fact[3],'*Fila',2)
        print('Pivoteo- A: =',M_A)
        print('Matriz elemental:=',Id1)
        print('Matriz inversa elemental',indice,':=',Idinv1)
        print('Producto Matrices inversa elemental: =',Aux_1)
        print('------------------------')
else: #Caso contrari se procede a pibotar
    for i in range(2,Fil): #Comienza desde fila 2 : [1,:]
        Id1=np.copy(Iden)
        M_A[i,:]=C_fact[i]*M_A[1,:]-C_fact[1]*M_A[i,:] #Fila2 =cofactor-fila1
        Id1[i,:]=C_fact[i]*Id1[1,:]-C_fact[1]*Id1[i,:] #Fila2 =cofactor-fila1
        #Idinv1=np.linalg.inv(Id1)
        print('Fila',i+1,':',C_fact[i],'*Fila 1-',C_fact[1],'*Fila',i+1)
        print('Pivoteo- A: =',M_A)
        print('Pivoteo- Identidad: =',Id1)
        print('------------------------')

cofactores 2da col= [ 3  0 10  7]
------------------
Matriz. permutada filas  [[-1  3  1  0]
 [ 0 10  3  1]
 [ 0  0  3  1]
 [ 0  7  2  0]]
Fila 4 : 10 *Fila 4- 7 *Fila 2
Pivoteo- A: = [[-1  3  1  0]
 [ 0 10  3  1]
 [ 0  0  3  1]
 [ 0  0 -1 -7]]
Matriz elemental:= [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -7.  0. 10.]]
Matriz inversa elemental 4 := [[ 1.   0.   0.   0. ]
 [-0.   1.  -0.  -0. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.7  0.   0.1]]
Producto Matrices inversa elemental: = [[ 1.   0.   0.   0. ]
 [-1.   1.   0.   0. ]
 [-3.   0.   1.   0. ]
 [-2.   0.7  0.   0.1]]
------------------------


In [5]:
C_fact=np.copy(M_A[:,2]) #Extrae los cofactores de  tercera columna
Id1=np.copy(Iden)  ## Crea matriz idenitidad auxiliar
M_A[3,:]=C_fact[2]*M_A[3,:]-C_fact[3]*M_A[2,:] #Fila4 =CF*F4-CF*F2
Id1[3,:]=C_fact[2]*Id1[3,:]-C_fact[3]*Id1[2,:] #Fila4 =CF*F4-CF*F2
Idinv1=np.linalg.inv(Id1)
Aux_2=np.matmul(Aux_1,Idinv1)
Aux_1=Aux_2
Aux_1=np.round(Aux_1)
print('Fila',4,':',C_fact[1],'*Fila 4-',C_fact[3],'*Fila',2)
print('Pivoteo- A: =',M_A)
print('Matriz elemental:=',Id1)
print('Matriz inversa elemental',indice,':=',Idinv1)
print('L: =',Aux_1)
U=np.copy(M_A)
print('U: =',U)

Fila 4 : 3 *Fila 4- -1 *Fila 2
Pivoteo- A: = [[ -1   3   1   0]
 [  0  10   3   1]
 [  0   0   3   1]
 [  0   0   0 -20]]
Matriz elemental:= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 3.]]
Matriz inversa elemental 4 := [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.         -0.33333333  0.33333333]]
L: = [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [-3.  0.  1.  0.]
 [-2.  1. -0.  0.]]
U: = [[ -1   3   1   0]
 [  0  10   3   1]
 [  0   0   3   1]
 [  0   0   0 -20]]


In [6]:
## otro metodo calcular L
Pinv=np.linalg.inv(Permuta)
Uinv=np.linalg.inv(U)
Y=np.matmul(A,Uinv)
print('Impresion de A*U-1',Y)
print('----------')
L=np.matmul(Pinv,Y)
L=np.round(L)
print('L:=',L)

Impresion de A*U-1 [[ 1.00000000e+00 -2.77555756e-17  5.55111512e-17  0.00000000e+00]
 [-1.00000000e+00  2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-3.00000000e+00  1.00000000e+00 -1.94289029e-16  0.00000000e+00]
 [-2.00000000e+00  7.00000000e-01 -3.33333333e-02  3.33333333e-02]]
----------
L:= [[ 1. -0.  0.  0.]
 [-3.  1. -0.  0.]
 [-1.  0.  1.  0.]
 [-2.  1. -0.  0.]]


In [7]:
#Comprobacion de las matrices P.L.U.
M1=np.matmul(L,U)
M2=np.matmul(Permuta,M1)
print(M2)

[[-1.  3.  1.  0.]
 [ 1. -3.  2.  1.]
 [ 3.  1.  0.  1.]
 [ 2.  4.  1.  1.]]
