## Matrices


In [13]:
import numpy as np

In [14]:
M_A = np.array([[2, -3, 5], 
              [6, -1, 3], 
              [-4, 1, -2]])
print('A=',M_A)

A= [[ 2 -3  5]
 [ 6 -1  3]
 [-4  1 -2]]


In [15]:
cf11=M_A[0,0]
print('cf1;',cf1)
cf21=M_A[1,0]
cf31=M_A[2,0]
M_A[1,:]=cf21*M_A[0,:]-cf11*M_A[1,:] #Fila2 =cofactor-fila1
print('A*Fila2=',M_A)
M_A[2,:]=cf31*M_A[0,:]-cf11*M_A[2,:] #Fila3 =cofactor-fila1
print('A*Fila3=',M_A)

cf1; 2
A*Fila2= [[  2  -3   5]
 [  0 -16  24]
 [ -4   1  -2]]
A*Fila3= [[  2  -3   5]
 [  0 -16  24]
 [  0  10 -16]]


In [16]:
cf22=M_A[1,1]
cf32=M_A[2,1]
M_A[2,:]=cf32*M_A[1,:]-cf22*M_A[2,:] #Fila3 =cofactor-fila1
print('A*FF=',M_A)

A*FF= [[  2  -3   5]
 [  0 -16  24]
 [  0   0 -16]]
