## Matrices


In [20]:
import numpy as np

In [21]:
def multiply_matrix(A,B):
  global C
  if  A.shape[1] == B.shape[0]:
    C = np.zeros((A.shape[0],B.shape[1]),dtype = int)
    for row in range(rows): 
        for col in range(cols):
            for elt in range(len(B)):
              C[row, col] += A[row, elt] * B[elt, col]
    return C
  else:
    return "Sorry, cannot multiply A and B."


In [38]:
M_A = np.array([[-1, 3,1,0], 
              [1,-3,2,1], 
              [3,1,0,1],
             [2,1,0,0]])
print('A=',M_A)

A= [[-1  3  1  0]
 [ 1 -3  2  1]
 [ 3  1  0  1]
 [ 2  1  0  0]]


In [39]:
cf11=M_A[0,0]
print('cf1;',cf11)
cf21=M_A[1,0]
print('cf2;',cf21)
cf31=M_A[2,0]
print('cf3;',cf31)
cf41=M_A[3,0]
print('cf4;',cf41)
M_A[1,:]=M_A[0,:]+M_A[1,:] #Fila2 =cofactor-fila1
print('A*Fila2=',M_A)
M_A[2,:]=3*M_A[0,:]+M_A[2,:] #Fila3 =cofactor-fila1
print('A*Fila3=',M_A)
M_A[3,:]=2*M_A[0,:]+M_A[3,:] #Fila4 =cofactor-fila1
print('A*Fila4=',M_A)

cf1; -1
cf2; 1
cf3; 3
cf4; 2
A*Fila2= [[-1  3  1  0]
 [ 0  0  3  1]
 [ 3  1  0  1]
 [ 2  1  0  0]]
A*Fila3= [[-1  3  1  0]
 [ 0  0  3  1]
 [ 0 10  3  1]
 [ 2  1  0  0]]
A*Fila4= [[-1  3  1  0]
 [ 0  0  3  1]
 [ 0 10  3  1]
 [ 0  7  2  0]]


In [45]:
M_B = np.array([[-1, 3,1,0], 
              [0,10,3,1], 
              [0,0,3,1],
             [0,7,2,0]])
print('B=',M_B)

B= [[-1  3  1  0]
 [ 0 10  3  1]
 [ 0  0  3  1]
 [ 0  7  2  0]]


In [46]:
M_B[3,:]=10*M_B[3,:]-7*M_B[1,:] #Fila4 =cofactor-fila1
print('A*Fila44=',M_B)
M_B[3,:]=3*M_B[3,:]+M_B[2,:] #Fila4 =cofactor-fila1
print('A*Fila44=',M_B)

A*Fila44= [[-1  3  1  0]
 [ 0 10  3  1]
 [ 0  0  3  1]
 [ 0  0 -1 -7]]
A*Fila44= [[ -1   3   1   0]
 [  0  10   3   1]
 [  0   0   3   1]
 [  0   0   0 -20]]


In [61]:
Id=np.array([[1, 0,0,0], 
              [0,1,0,0], 
              [0,0,1,0],
             [0,0,0,1]])
print('I=',Id)
Id[1,:]=Id[0,:]+Id[1,:] #Fila2 =cofactor-fila1
print('A*Fila2=',Id)
Idinv1=np.linalg.inv(Id)
print('ej inv=',Idinv1)

I= [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
A*Fila2= [[1 0 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
ej inv= [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [62]:
Id=np.array([[1, 0,0,0], 
              [0,1,0,0], 
              [0,0,1,0],
             [0,0,0,1]])

Id[2,:]=3*Id[0,:]+Id[2,:] #Fila3 =cofactor-fila1
print('A*Fila3=',Id)
Idinv2=np.linalg.inv(Id)
print('ej inv2=',Idinv2)
Id=np.array([[1, 0,0,0], 
              [0,1,0,0], 
              [0,0,1,0],
             [0,0,0,1]])
Id[3,:]=2*Id[0,:]+Id[3,:] #Fila4 =cofactor-fila1
print('A*Fila4=',Id)
Idinv3=np.linalg.inv(Id)
print('ej inv3=',Idinv3)

A*Fila3= [[1 0 0 0]
 [0 1 0 0]
 [3 0 1 0]
 [0 0 0 1]]
ej inv2= [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-3. -0.  1. -0.]
 [ 0.  0.  0.  1.]]
A*Fila4= [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [2 0 0 1]]
ej inv3= [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-2. -0. -0.  1.]]


In [66]:
Id2=np.array([[1, 0,0,0], 
              [0,0,1,0], 
              [0,1,0,0],
             [0,0,0,1]])
print('I=',Id2)
Idinv4=np.linalg.inv(Id2)
print('ej inv4=',Idinv4)

I= [[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]
ej inv4= [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [67]:
Id=np.array([[1, 0,0,0], 
              [0,1,0,0], 
              [0,0,1,0],
             [0,0,0,1]])
Id[3,:]=10*Id[3,:]-7*Id[1,:] #Fila4 =cofactor-fila1
print('A*Fila44=',Id)
Idinv5=np.linalg.inv(Id)
print('ej inv5=',Idinv5)

Id=np.array([[1, 0,0,0], 
              [0,1,0,0], 
              [0,0,1,0],
             [0,0,0,1]])
Id[3,:]=3*Id[3,:]+Id[2,:] #Fila4 =cofactor-fila1
print('A*Fila44=',Id)
Idinv6=np.linalg.inv(Id)
print('ej inv6=',Idinv6)

A*Fila44= [[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0 -7  0 10]]
ej inv5= [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-0.00000000e+00  1.00000000e+00 -0.00000000e+00  7.93016446e-18]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  7.00000000e-01  0.00000000e+00  1.00000000e-01]]
A*Fila44= [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 3]]
ej inv6= [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.         -0.33333333  0.33333333]]
